name: Sample

on:
  workflow_dispatch:

jobs:
  sample:
    uses: "yk-mt12/reusable-workflow/.github/workflows/notify-slack.yaml@master"
    with:
      message: test sample
    secrets:
      slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
      slack_channel_ids: ${{ secrets.SLACK_CHANNEL_IDS }}
